var dir_4c3ebd39004e28fab2aec004563a84b1 =
[
    [ "Editor", "dir_7b97d35913e8153cea81e41023dac803.html", "dir_7b97d35913e8153cea81e41023dac803" ],
    [ "AutomatableSlots.cs", "AutomatableSlots_8cs.html", "AutomatableSlots_8cs" ],
    [ "BankRefAttribute.cs", "BankRefAttribute_8cs.html", "BankRefAttribute_8cs" ],
    [ "EventHandler.cs", "EventHandler_8cs.html", "EventHandler_8cs" ],
    [ "EventRefAttribute.cs", "EventRefAttribute_8cs.html", "EventRefAttribute_8cs" ],
    [ "EventReference.cs", "EventReference_8cs.html", "EventReference_8cs" ],
    [ "fmod.cs", "fmod_8cs.html", "fmod_8cs" ],
    [ "fmod_dsp.cs", "fmod__dsp_8cs.html", "fmod__dsp_8cs" ],
    [ "fmod_errors.cs", "fmod__errors_8cs.html", "fmod__errors_8cs" ],
    [ "fmod_studio.cs", "fmod__studio_8cs.html", "fmod__studio_8cs" ],
    [ "FMODEventPlayable.cs", "FMODEventPlayable_8cs.html", null ],
    [ "FMODEventTrack.cs", "FMODEventTrack_8cs.html", null ],
    [ "FMODRuntimeManagerOnGUIHelper.cs", "FMODRuntimeManagerOnGUIHelper_8cs.html", "FMODRuntimeManagerOnGUIHelper_8cs" ],
    [ "ParamRef.cs", "ParamRef_8cs.html", "ParamRef_8cs" ],
    [ "ParamRefAttribute.cs", "ParamRefAttribute_8cs.html", "ParamRefAttribute_8cs" ],
    [ "Platform.cs", "Platform_8cs.html", "Platform_8cs" ],
    [ "PlatformDefault.cs", "PlatformDefault_8cs.html", "PlatformDefault_8cs" ],
    [ "PlatformGroup.cs", "PlatformGroup_8cs.html", "PlatformGroup_8cs" ],
    [ "PlatformMobileHigh.cs", "PlatformMobileHigh_8cs.html", "PlatformMobileHigh_8cs" ],
    [ "PlatformMobileLow.cs", "PlatformMobileLow_8cs.html", "PlatformMobileLow_8cs" ],
    [ "PlatformPlayInEditor.cs", "PlatformPlayInEditor_8cs.html", "PlatformPlayInEditor_8cs" ],
    [ "RuntimeManager.cs", "RuntimeManager_8cs.html", "RuntimeManager_8cs" ],
    [ "RuntimeUtils.cs", "RuntimeUtils_8cs.html", "RuntimeUtils_8cs" ],
    [ "Settings.cs", "Settings_8cs.html", "Settings_8cs" ],
    [ "StudioBankLoader.cs", "StudioBankLoader_8cs.html", "StudioBankLoader_8cs" ],
    [ "StudioEventEmitter.cs", "StudioEventEmitter_8cs.html", "StudioEventEmitter_8cs" ],
    [ "StudioGlobalParameterTrigger.cs", "StudioGlobalParameterTrigger_8cs.html", "StudioGlobalParameterTrigger_8cs" ],
    [ "StudioListener.cs", "StudioListener_8cs.html", "StudioListener_8cs" ],
    [ "StudioParameterTrigger.cs", "StudioParameterTrigger_8cs.html", "StudioParameterTrigger_8cs" ]
];