var hierarchy =
[
    [ "AchievementService", "classAchievementService.html", null ],
    [ "AppDataPaths", "classAppDataPaths.html", null ],
    [ "AudioVolume", "classAudioVolume.html", null ],
    [ "ChartEditorTime.BarInfo", "structChartEditorTime_1_1BarInfo.html", null ],
    [ "BulletPlacement", "classBulletPlacement.html", null ],
    [ "ChartEditorDocument", "classChartEditorDocument.html", null ],
    [ "ChartEditorDraw", "classChartEditorDraw.html", null ],
    [ "ChartEditorJson", "classChartEditorJson.html", null ],
    [ "ChartEditorNotes", "classChartEditorNotes.html", null ],
    [ "ChartEditorSettings", "classChartEditorSettings.html", null ],
    [ "ChartEditorSong", "classChartEditorSong.html", null ],
    [ "ChartEditorTime", "classChartEditorTime.html", null ],
    [ "ChartEditorUi", "classChartEditorUi.html", null ],
    [ "ChartEventDispatcher", "classChartEventDispatcher.html", null ],
    [ "ChartHashUtility", "classChartHashUtility.html", null ],
    [ "ChartImporter", "classChartImporter.html", null ],
    [ "ChartTimelineRuntime", "classChartTimelineRuntime.html", null ],
    [ "CurveUtil", "classCurveUtil.html", null ],
    [ "DeveloperSettings", "classDeveloperSettings.html", null ],
    [ "DifficultyColorPalette", "classDifficultyColorPalette.html", null ],
    [ "DifficultyInfo", "classDifficultyInfo.html", null ],
    [ "EaseUtil", "classEaseUtil.html", null ],
    [ "GameSavePaths", "classGameSavePaths.html", null ],
    [ "GameSettingsSaveManifest", "classGameSettingsSaveManifest.html", null ],
    [ "GameSettingsSaveService", "classGameSettingsSaveService.html", null ],
    [ "Graphic", null, [
      [ "UITrailGraphic", "classUITrailGraphic.html", null ]
    ] ],
    [ "IDisposable", null, [
      [ "ParrythmInputActions", "classParrythmInputActions.html", null ],
      [ "ParrythmInputRuntime.StateOverrideHandle", "classParrythmInputRuntime_1_1StateOverrideHandle.html", null ],
      [ "ParrythmVirtualPointer", "classParrythmVirtualPointer.html", null ]
    ] ],
    [ "IGaugeCommand", "interfaceIGaugeCommand.html", [
      [ "GaugeManager", "classGaugeManager.html", null ]
    ] ],
    [ "ILeaderboardService", "interfaceILeaderboardService.html", [
      [ "LocalLeaderboardSaveService", "classLocalLeaderboardSaveService.html", null ]
    ] ],
    [ "ParrythmInputActions.IngameGameplayActions", "classParrythmInputActions_1_1IngameGameplayActions.html", null ],
    [ "INoteEventHandler", "interfaceINoteEventHandler.html", [
      [ "BulletNoteHandler", "classBulletNoteHandler.html", null ],
      [ "CameraEventHandler", "classCameraEventHandler.html", null ],
      [ "CircleTapHandler", "classCircleTapHandler.html", null ],
      [ "GridNoteHandler", "classGridNoteHandler.html", null ],
      [ "ImageEventHandler", "classImageEventHandler.html", null ],
      [ "LongNoteHandler", "classLongNoteHandler.html", null ],
      [ "SliderNoteHandler", "classSliderNoteHandler.html", null ],
      [ "StyleEventHandler", "classStyleEventHandler.html", null ],
      [ "VoiceEventHandler", "classVoiceEventHandler.html", null ]
    ] ],
    [ "INoteInit< TInit >", "interfaceINoteInit.html", null ],
    [ "IStageEndTrigger", "interfaceIStageEndTrigger.html", [
      [ "ChartEndWatcher", "classChartEndWatcher.html", null ]
    ] ],
    [ "Notes.Lane.LaneUtil", "classNotes_1_1Lane_1_1LaneUtil.html", null ],
    [ "LeaderboardRecord", "classLeaderboardRecord.html", null ],
    [ "LeaderboardScoreUploadDto", "classLeaderboardScoreUploadDto.html", null ],
    [ "LeaderboardServiceProvider", "classLeaderboardServiceProvider.html", null ],
    [ "LevelChartData", "classLevelChartData.html", null ],
    [ "LevelChartJsonTool", "classLevelChartJsonTool.html", null ],
    [ "LocalizationHelper", "classLocalizationHelper.html", null ],
    [ "LocalLeaderboardSaveData", "classLocalLeaderboardSaveData.html", null ],
    [ "LocalScoreRecord", "classLocalScoreRecord.html", null ],
    [ "LocalScoreSaveData", "classLocalScoreSaveData.html", null ],
    [ "LocalScoreSaveService", "classLocalScoreSaveService.html", null ],
    [ "LocalSettingsSaveStorage", "classLocalSettingsSaveStorage.html", null ],
    [ "MenuTypingLock", "classMenuTypingLock.html", null ],
    [ "MeshUtil", "classMeshUtil.html", null ],
    [ "Mods", "classMods.html", null ],
    [ "MonoBehaviour", null, [
      [ "AnimatedCharacterController", "classAnimatedCharacterController.html", null ],
      [ "AnimatedCharacterPicker", "classAnimatedCharacterPicker.html", null ],
      [ "ApproachCircleVisual", "classApproachCircleVisual.html", null ],
      [ "AutoPlayController", "classAutoPlayController.html", null ],
      [ "BattleAnimationReaction", "classBattleAnimationReaction.html", null ],
      [ "BulletNote", "classBulletNote.html", null ],
      [ "CameraTweenTrack", "classCameraTweenTrack.html", null ],
      [ "ChartEditorController", "classChartEditorController.html", null ],
      [ "ChartEndWatcher", "classChartEndWatcher.html", null ],
      [ "ChartPlayer", "classChartPlayer.html", null ],
      [ "CircleNoteVisual", "classCircleNoteVisual.html", null ],
      [ "CleanCursor", "classCleanCursor.html", null ],
      [ "ConnectionHintController", "classConnectionHintController.html", null ],
      [ "Fixed16x9Camera", "classFixed16x9Camera.html", null ],
      [ "FmodMusicControllerLegacy", "classFmodMusicControllerLegacy.html", null ],
      [ "GameBootstrap", "classGameBootstrap.html", null ],
      [ "GaugeManager", "classGaugeManager.html", null ],
      [ "GridDrawer", "classGridDrawer.html", null ],
      [ "GridManager", "classGridManager.html", null ],
      [ "InputRouter", "classInputRouter.html", null ],
      [ "InputTimeMapper", "classInputTimeMapper.html", null ],
      [ "Judge", "classJudge.html", null ],
      [ "KeyboardInputManager", "classKeyboardInputManager.html", null ],
      [ "NoteBase", "classNoteBase.html", [
        [ "CircleNote", "classCircleNote.html", null ],
        [ "SliderNote", "classSliderNote.html", null ]
      ] ],
      [ "NoteSpawner", "classNoteSpawner.html", null ],
      [ "Notes.Lane.LaneOccupancyProvider", "classNotes_1_1Lane_1_1LaneOccupancyProvider.html", null ],
      [ "Notes.Lane.LaneRouter", "classNotes_1_1Lane_1_1LaneRouter.html", null ],
      [ "Notes.Square.SquareNoteCore", "classNotes_1_1Square_1_1SquareNoteCore.html", null ],
      [ "Notes.Square.SquareNoteJudge", "classNotes_1_1Square_1_1SquareNoteJudge.html", null ],
      [ "Notes.Square.SquareNoteTimeline", "classNotes_1_1Square_1_1SquareNoteTimeline.html", null ],
      [ "Notes.Square.SquareNoteVisual", "classNotes_1_1Square_1_1SquareNoteVisual.html", null ],
      [ "Notes.Square.SquareVisualBase", "classNotes_1_1Square_1_1SquareVisualBase.html", [
        [ "Notes.Square.SquareVisualNormal", "classNotes_1_1Square_1_1SquareVisualNormal.html", null ],
        [ "Notes.Square.SquareVisualTrail", "classNotes_1_1Square_1_1SquareVisualTrail.html", null ]
      ] ],
      [ "Notes.Square.SquareVisualLong", "classNotes_1_1Square_1_1SquareVisualLong.html", null ],
      [ "OutgameBootstrap", "classOutgameBootstrap.html", null ],
      [ "ParrythmInputRuntime", "classParrythmInputRuntime.html", null ],
      [ "PauseScreenController", "classPauseScreenController.html", null ],
      [ "PlayerSpriteController", "classPlayerSpriteController.html", null ],
      [ "RatingLabel", "classRatingLabel.html", null ],
      [ "ResultScreenController", "classResultScreenController.html", null ],
      [ "SettingsScreenController", "classSettingsScreenController.html", null ],
      [ "SliderNoteVisual", "classSliderNoteVisual.html", null ],
      [ "SongPreviewPlayer", "classSongPreviewPlayer.html", null ],
      [ "SongSelectController", "classSongSelectController.html", null ],
      [ "TitleScreenController", "classTitleScreenController.html", null ],
      [ "UnityMusicController", "classUnityMusicController.html", null ]
    ] ],
    [ "MusicAudioPathResolver", "classMusicAudioPathResolver.html", null ],
    [ "LevelChartData.NoteEvent", "classLevelChartData_1_1NoteEvent.html", null ],
    [ "NoteSpeedScale", "classNoteSpeedScale.html", null ],
    [ "ParrythmInputActions.OutgameMenuActions", "classParrythmInputActions_1_1OutgameMenuActions.html", null ],
    [ "OutgameMenuInput", "classOutgameMenuInput.html", null ],
    [ "OutgameNavigator", "classOutgameNavigator.html", null ],
    [ "OutgameOverlay", "classOutgameOverlay.html", null ],
    [ "OutgameSfx", "classOutgameSfx.html", null ],
    [ "SpecialBulletPattern.Params", "classSpecialBulletPattern_1_1Params.html", null ],
    [ "PlayerNameSettings", "classPlayerNameSettings.html", null ],
    [ "PlayerPreferences", "classPlayerPreferences.html", null ],
    [ "PlayerPreferencesService", "classPlayerPreferencesService.html", null ],
    [ "PlayFinishedInput", "structPlayFinishedInput.html", null ],
    [ "PlayPrefsService", "classPlayPrefsService.html", null ],
    [ "ProfileSaveData", "classProfileSaveData.html", null ],
    [ "RatingEntry", "structRatingEntry.html", null ],
    [ "RatingService", "classRatingService.html", null ],
    [ "ParrythmInputActions.ResultsMenuActions", "classParrythmInputActions_1_1ResultsMenuActions.html", null ],
    [ "SaveIdentity", "classSaveIdentity.html", null ],
    [ "SceneNames", "classSceneNames.html", null ],
    [ "ScoreGradeUtility", "classScoreGradeUtility.html", null ],
    [ "SongEntry", "classSongEntry.html", null ],
    [ "SongMeta", "classSongMeta.html", null ],
    [ "SongScanner", "classSongScanner.html", null ],
    [ "SpecialBulletPattern", "classSpecialBulletPattern.html", null ],
    [ "StageBackground", "classStageBackground.html", null ],
    [ "LevelChartData.TempoPoint", "classLevelChartData_1_1TempoPoint.html", null ],
    [ "LevelChartData.TimeSigPoint", "classLevelChartData_1_1TimeSigPoint.html", null ],
    [ "BulletPlacement.Triplet", "structBulletPlacement_1_1Triplet.html", null ],
    [ "ParrythmInputActions.UIActions", "classParrythmInputActions_1_1UIActions.html", null ],
    [ "VisualElement", null, [
      [ "MarkSplashParticles", "classMarkSplashParticles.html", null ],
      [ "MiniMapView", "classMiniMapView.html", null ],
      [ "NumField", "classNumField.html", null ],
      [ "PreviewView", "classPreviewView.html", null ],
      [ "WaveformView", "classWaveformView.html", null ]
    ] ]
];